# Generated by Django 4.1 on 2022-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.DateField(),
        ),
    ]
